name = "rusty_sak"
product-name = "RustySak"
identifier = "com.thecodechef.rusty-sak"
version = "0.1.0"
out-dir = "./dist"
description = "A version of SAK written in rust"
copyright = "Copyright © 2024 Jeremy Bolding, All Rights Reserved"
category = "Developer Tools"
homepage = "https://rusty-sak.github.io/"
formats = ["default"]
icons = ["resources/ios/colorized/rusty_sak-logo-colorized-512x512.png"]
before-packaging-command = "cargo build --release"

[[binaries]]
  main = true
  path = "target/release/rusty_sak"

# [appimage]
# [deb]

# [nsis]

# [dmg]
# [macos]