import { Palette, VerticalBox, AboutSlint } from "std-widgets.slint";

component CloseButton inherits Rectangle {
  in-out property text <=> txt.text;
  callback clicked <=> touch.clicked;

  height: 30px;
  width: 200px;
  background: touch.has-hover ? Palette.alternate-foreground : #666;
  border-radius: 2px;


  txt := Text {
    color: touch.has-hover ? Palette.background : Palette.alternate-foreground;
  }
  touch := TouchArea {}

}

export component InfoWindow inherits Window {
    min-height: 400px;
    min-width: 300px;
    title: "RustySAK - Info";
    VerticalBox {
      HorizontalLayout {
        alignment: center;
        Image {
          image-fit: contain;
          height: 80px;
          width: 80px;
          source: @image-url("../resources/logo.png");
        }
      }
      HorizontalLayout {
        alignment: center;
        VerticalLayout {
          Text {
            text: "RustySAK\nv0.1.0";
            font-size: 16px;
            font-weight: 500;
            horizontal-alignment: center;
          }
        }
      }
      HorizontalLayout {
        alignment: center;
        AboutSlint {}
      }
      HorizontalLayout {
        alignment: center;
        Rectangle {
          width: 200px;
          height: 30px;
          callback close_window();
          CloseButton {
            text: "Close";
            clicked => { parent.close_window() }
          }
        }
      }
    }
}